CREATE DATABASE IF NOT EXISTS product;
USE product;

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  dueDate DATE NOT NULL,
  status VARCHAR(50) DEFAULT 'Draft',
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoiceIdTable (
  clientName VARCHAR(255) NOT NULL,
  invoiceId DECIMAL(10, 2) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);